# JWT Configuration
app.jwt.secret=bXktc3VwZXItc2VjcmV0LWtleS0zMi1jaGFyYWN0ZXJzISE=
app.jwt.expiration-ms=86400000
# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/cafe_schedule
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Server
server.port=8080
logging.level.cafe=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
# === Swagger / OpenAPI ????????? ===
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.default-models-expand-depth=-1
# ??????????? ?????????? ?? ????? (???????????)
springdoc.swagger-ui.urls-primary-name=cafe-api
# ?????????? ?????????? ?????????? ?? ????????????
springdoc.packages-to-scan=cafe.controller
springdoc.paths-to-match=/api/**
# JWT: ????????? ?????? ??????????? ? Swagger
springdoc.swagger-ui.try-it-out-enabled=true